var questionAnswer = {}
questionAnswer["Người ta lưu hồ sơ của cán bộ có mục tên, tuổi, quê quán, là đoàn viên hay không, đã có gia đình chưa, ảnh, số giấy chứng minh. Dữ liệu tuổi thuộc loại"] = "Số";
questionAnswer["Âm thanh có thể mã hoá dưới dạng số được không"] = "Có";
questionAnswer["Trong dữ liệu ảnh, màu được tạo từ các màu cơ bản nào"] = "Đỏ Xanh dương và Xanh lá cây (Red Blue Green)";
questionAnswer["Người ta lưu hồ sơ của cán bộ có mục tên, tuổi, quê quán là đoàn viên hay không, đã có gia đình chưa, ảnh, số giấy chứng minh. Dữ liệu là đoàn viên thuộc loại"] = "Logic";
questionAnswer["Tuyệt đại đa số các máy tính sử dụng cấu trúc địa chỉ hoá tới byte. Byte thường được dùng để lưu trữ một chữ. Gần đây người ta dùng nhiều đến UNICODE mà mỗi trang mã có thể dùng đến 2 byte cho một ký tự. Lý do nào là lý do xác đáng nhất với việc tạo ra UNICODE là"] = "Tạo ra một bộ mã thống nhất toàn cầu trong đó mỗi quốc gia có quyền thừa hưởng các ký tự đã có cũng như có thể khai báo đủ các ký tự riêng liên quan đến bộ chữ của mình";
questionAnswer["Người ta lưu hồ sơ của cán bộ có mục tên, tuổi, quê quán, là đoàn viên hay không, đã có gia đình chưa, ảnh, số giấy chứng minh. Dữ liệu số giấy chứng minh thuộc loại"] = "Văn bản";
questionAnswer["Chúng ta đã biết, chuẩn dấu phảy động IEEE 754 có những điều chỉnh so với kiểu dấu phảy động ban đầu. Phát biểu nào dưới đây sai"] = "Số dấu phảy động theo chuẩn IEEE 754 đưa vào đặc tả riêng cho số khác 0";
questionAnswer["Chúng ta đã biết, chuẩn dấu phảy động IEEE 754 có những điều chỉnh so với kiểu dấu phảy động ban đầu. Phát biểu nào sai dưới đây"] = "Số dấu phảy động theo chuẩn IEEE 754 đưa vào biểu diễn số nguyên";
questionAnswer["Bản chất âm thanh là tín hiệu tương tự (analog) chứ không phải tín hiệu số (digital). Âm thanh khi đưa vào máy tính là loại nào"] = "Số";
questionAnswer["Người ta lưu hồ sơ của cán bộ có mục tên, tuổi, quê quán, là đoàn viên hay không, đã có gia đình chưa, ảnh, số giấy chứng minh. Dữ liệu tình trạng gia đình thuộc loại"] = "Logic";
questionAnswer["Người ta lưu hồ sơ đăng ký xe máy bằng máy tính trong đó có các mục tên chủ xe, ngày sinh, địa chỉ, số khung, số máy, biển số, dung tích xy lanh, hãng sản xuất, kiểu xe. Dữ liệu biển số thuộc loại nào"] = "Văn bản";
questionAnswer["Sau đây là một số ý kiên sinh viên đưa ra về lý do dùng số dấu phảy động. Điều nào sai"] = "Để tiết kiệm bộ nhớ";
questionAnswer["Số nguyên có biểu diễn được ở dưới dạng dấu phảy động được không"] = "Có";
questionAnswer["Có thể kết hợp cả hai phương pháp điều chế để mã hoá tín hiệu hay không"] = "Có thể kết hợp điều pha và điều biên";
questionAnswer["Khi biểu diễn giá trị logic, có những ý kiến sau, ý kiến nào kém thuyết phục hơn cả"] = "Tuỳ theo các hệ thống dùng từ máy dài bao nhiêu 8 bít, 16 bít, 32 bít";
questionAnswer["Có những ý kiến sau về dùng số dấu phảy động"] = "Ý kiến 1 và ý kiến 3";
questionAnswer["Người ta lưu hồ sơ của cán bộ có mục tên, tuổi, quê quán, là đoàn viên hay không, đã có gia đình chưa, ảnh, số giấy chứng minh. Dữ liệu ảnh thuộc loại"] = "Đa phương tiện";
questionAnswer["Bảng chữ UNICODE theo kiểu dựng sẵn cho tiếng Việt sử dụng 2 byte. Bảng chữ này có khả năng thể hiện"] = "Nhiều hơn 256 ký tự";
questionAnswer["Người ta lưu hồ sơ của cán bộ có mục tên, tuổi, quê quán, là đoàn viên hay không, đã có gia đình chưa, ảnh, số giấy chứng minh. Dữ liệu tên thuộc loại"] = "Văn bản";
questionAnswer["Điều tần là phương pháp mã hoá tín hiệu dựa trên"] = "Tần số của sóng mang tín hiệu";
questionAnswer["Dữ liệu đa phương tiện là dữ liệu"] = "Là dữ liệu âm thanh hay hình ảnh";

questionAnswer["Có người đề xuất cách giải bài toán cổ \"Trăm trâu trăm bó cỏ. Trâu đứng ăn 5; trâu nằm ăn 3; trâu gia 3 con ăn 1. Hỏi mỗi loại trâu có bao nhiêu con?\" như sau:"] = "Quá trình mô tả trên là một giải thuật";
questionAnswer["Có một phương pháp tính gọi là Monter-Carlo để tính dựa vào các đặc trưng xác xuất, người ta phải chế ra các số ngẫu nhiên. Mỗi khi yêu cầu, máy tính lại đưa ra một con số không dự đoán được trước. Có thể nói rằng bài toán đưa ra một số ngẫu nhiên có thuật toán vi phạm tính xác định không?"] = "Không";
questionAnswer["Một người viết chương trình chơi cờ vua. Bài toán chơi cờ có output là:"] = "Nước đi của máy và thời gian đi tương ứng với mỗi nước của máy";
questionAnswer["Một người viết chương trình chơi cờ vua. Bài toán chơi cờ có input là"] = "Nước đi của người chơi, thời gian đi từng nước của người chơi và thời gian chơi của máy đối với từng nước đi của nó";
questionAnswer["Tính khả thi của thuật toán được hiểu là"] = "Có thể thực hiện được";
questionAnswer["Độ phức tạp của thuật toán không phụ thuộc vào?"] = "Tốc độ tính toán của máy tính thực hiện thuật toán.";
questionAnswer["Xét các cách tìm USCLN của hai số tự nhiên m và n qua các giải thuật sau đây"] = "Cách 3";
questionAnswer["Cho một dãy số tăng dần x1, x2, ... xn và một số a nào đó. Xác định có chỉ số i nào để a= xi. Sau đây là một số thuật toán tìm kiếm nhị phân với 5 bước từ 1 đến 5. Cho trước 3 bước đầu. Có tới 3 phương án cho bước 4 và 5 như sau:"] = "Cả 3 phương án trên đều đúng";
questionAnswer["Cho số tự nhiên m, tính n theo quá trình sau"] = "m bình phương";
questionAnswer["Tính dừng của thuật toán được hiểu là"] = "Thuật toán phải quy định những điều kiện để đảm bảo tính toán phải dừng sau một số hữu hạn bước";
questionAnswer["Cho một số x và một dãy l các số a1, a2…ai… ak được xếp theo chiều tăng dần. Ta thi hành thụât toán xác định x có ở trong dãy không và nếu có thì ở vị trí nào"] = "Thuật toán luôn luôn dừng";
questionAnswer["Có n gói hàng đáng lẽ phải nặng như nhau nhưng có một gói sai quy cách nhẹ hơn các gói khác. Một sinh viên đã viết giải thuật sau để tìm gói hàng này bằng cách dùng cân đĩa theo nguyên lý thăng bằng."] = "Giải thuật này đúng. Không cần phải sửa";
questionAnswer["Cho một dãy số tăng dần x1, x2, ... xn và một số a nào đó. Xác định có chỉ số i nào để a= xi. Sau đây là một số thuật toán tìm kiếm nhị phân à bước 3 và 4 có tới 3 phương án cho bới các nhóm phương án 1, 2,3"] = "Cả 3 phương án đều đúng.";
questionAnswer["Đâu không phải là đặc trưng của thuật toán?"] = "Thuật toán phải giải được mọi bài toán.";
questionAnswer["Cho thuật toán sau"] = "-Tính sin x theo khai triển Taylor đến số hạng thứ 50 \n-Tính ex theo khai triển Taylor đến số hạng thứ 100";
questionAnswer["Trong một trường học đã có cơ sở dữ liệu (hồ sơ trên máy tính) của tất cả học sinh trong trường. Bài toán in ra danh sách học sinh của lớp x nào đó có input là gì."] = "Có cả  \"Danh sách học sinh của cả trường\" và \"Tên của lớp X\"";
questionAnswer["Tính xác định của thuật toán có nghĩa là:"] = "Sau khi hoàn thành một bước (một chỉ dẫn), bước thực hiện tiếp theo hoàn toàn xác định";
questionAnswer["Có một giải thuật được mô tả như sau:"] = "m.n";
questionAnswer["Tính phổ dụng của thuật toán là"] = "Một thuật toán có thể ứng dụng cho nhiều input cùng loại";
questionAnswer["Một người mê tín. Trước khi đi chơi bao giờ anh ta cũng lấy quyển Kiều và làm theo các bước như sau"] = "Quá trình trên không phải là một giải thuật vì vi phạm tính xác định";
questionAnswer["Có người đề xuất cách giải bài toán sau"] = "Quá trình trên đúng là một giải thuật nhưng chưa đầy đủ vì cần thêm các buớc xử lý những trường hợp M, N chưa thích hợp";
questionAnswer["Giả sử một thuật toán được xác định bằng một số các chỉ dẫn. Tính xác định của thuật toán là"] = "Sau mỗi bước thực hiện một chỉ dẫn, với những input xác định, luôn xác định được duy nhất chỉ dẫn cần thực hiện tiếp theo";
questionAnswer["Xác đinh Input của bài toán tìm tất cả các số nguyên tố nhỏ hơn một số cho trước"] = "Số cho trước";

questionAnswer["Định nghĩa nào xác đáng nhất về ngôn ngữ bậc cao (ngôn ngữ thuật toán)"] = "Ngôn ngữ dưới dạng văn bản thể thiện thuật toán theo những quy ước không phụ thuộc vào các máy tính cụ thể";
questionAnswer["Đánh dấu vào câu sai"] = "Để máy tính có thể chạy được các chương trình trên các ngôn ngữ nói trong A, B, C đều phải cần một chương trình dịch dịch ra dưới dạng máy tính có thể thực hiện được";
questionAnswer["Ngôn ngữ lập trình là"] = "-Là phương tiện diễn đạt các giải thuật để chuyển giao cho máy tính thực hiện \n-Là quy ước để diễn tả thuật toán để máy tính có thể thực hiện đựợc trực tiếp hay qua một biến đổi có thể tự động hoá được";
questionAnswer["Có thể hiểu lỗi ngữ nghĩa là lỗi gây ra những tình trạng làm cho máy tính không thể chạy bình thường hoặc làm cho máy chạy sai ý định. Có phải lỗi ngữ nghĩa nào cũng được máy tính tự phát hiện khi chạy tương tự như lỗi chia cho 0 hay không."] = "Không";
questionAnswer["Điều nào là đúng trong các kết luận sau khi trả lời câu hỏi \"Sự khác nhau giữa biên dịch (compiler) và thông dịch (interpreter) là\""] = "Thông dịch không cần tạo mã mà chạy đến lệnh nào thì tạo các lệnh để thi hành còn biên dịch phải dịch trước toàn bộ chương trình sang nhị phần thì mới có thể chạy được";
questionAnswer["Câu nào đúng nhất trong định nghĩa một ngôn ngữ lập trình nói chung"] = "Là ngôn ngữ diễn đạt giải thuật để có thể giao cho máy tính thực hiện";
questionAnswer["Các phần mềm sau đây, phần mềm nào là chương trình dịch"] = "Turbo Pascal hay Microsoft C";
questionAnswer["Ngôn ngữ máy là"] = "Là ngôn ngữ thể hiện các chương trình mà mỗi chương trình là một dãy lệnh máy trong hệ nhị phân";
questionAnswer["Mục đích của phân tích cú pháp là"] = "Phát hiện ra các lỗi không đúng quy cách của chương trình";
questionAnswer["Bàn về các loại ngôn ngữ lập trình có các ý kiến sau đây. Theo bạn ý kiến nào xác đáng nhất"] = "Tuỳ từng trường hợp. Nói chung nên dùng ngôn ngữ bậc cao phù hợp với lĩnh vực ứng dụng vì hiệu suất phát triển phần mềm là cao nhất. Chỗ nào cần tối ưu mã chương trình thì mới dùng hợp ngữ. Nói chung không cần sử dụng ngôn ngữ máy vì hợp ngữ hầu như đã thể hiện chính ngôn ngữ máy";
questionAnswer["Mục đích của phân tích từ vựng là"] = "Phát hiện ra các đối tượng để lập danh mục các đối tượng";
questionAnswer["Có các khẳng định sau đây về chương trình dịch (comliler), khẳng định nào sai:"] = "Chương trình dịch giúp tìm ra tất cả các lỗi của chương trình";
questionAnswer["Chọn phương án tốt nhất trong định nghĩa về hợp ngữ (assembly). Hợp ngữ là loại ngôn ngữ"] = "Là ngôn ngữ có các lệnh được viết trong mã chữ nhưng về cơ bản mỗi lệnh tương đương với một một lệnh máy. Để chạy được cần dịch ra ngôn ngữ máy";
questionAnswer["Ngôn ngữ lập trình là một hệ thống ký hiệu và các quy tắc diễn đạt thuật toán để máy tính có thể hiểu được. Cách diễn đạt thuật toán bằng chỉ dẫn có thể coi là một ngôn ngữ lập trình hay không"] = "Không";
questionAnswer["Câu nào sau đây mô tả không chính xác về chương trình dịch :"] = "Trong quá trình dịch sẽ phát hiện lỗi ngữ nghĩa của chương trình nguồn.";
questionAnswer["Trong các ý kiến sau, ý kiến nào xác đáng hơn cả"] = "Tuỳ từng trường hợp, nhưng nói chung nên dùng ngôn ngữ bậc cao để tăng hiệu suất phát triển phần mềm";
questionAnswer["Ngôn ngữ lập trình là một hệ thống ký hiệu và các quy tắc diễn đạt thuật toán để máy tính có thể hiểu được. Cách diễn đạt bằng sơ đồ khối có thể coi là một ngôn ngữ lập trình hay không"] = "Không";
questionAnswer["Có các khẳng định sau đây về chương trình dịch, khẳng định nào sai:"] = "Chương trình dịch giúp tìm ra tất cả các lỗi của chương trình";
questionAnswer["Câu nào đúng khi nói về hợp ngữ?"] = "Hợp ngữ có thể viết lệnh dưới dạng mã chữ tiếng Anh.";
questionAnswer["Quá trình dịch chỉ tạo ra các mô đun đối tượng. Để có một chương trình duy nhất, hoàn chỉnh và có thể chạy được còn cần phải liên kết (link). Trong các phát biểu sau, phát biểu nào sai:"] = "Quá trình liên kết không bao giờ có lỗi";
questionAnswer["Các phần mềm sau đây, phần mềm nào là chương trình dịch"] = "Turbo Pascal hay Microsoft C";

questionAnswer["Mục đích của xử lý theo lô là"] = "Cả “Để người sử dụng có thể gửi cả một gói công việc một lần để đỡ tốn thời gian” và “Để liên kết được các công việc với nhau , công việc truớc có thể để lại dữ liệu và trạng thái xử lý cho công việc sau tiếp tục thực hiện”";
questionAnswer["Cơ chế plug and play là cơ chế"] = "Có cơ chế tự động phát hiện các thiết bị mới và tự động cảnh báo hoặc bổ sung chương trình điều khiển cho thiết bị mới";
questionAnswer["Trong hệ điều hành DOS, người ta có thể chạy các chương trình thường trú. Một khi chạy, các chương trình thường trú sẽ không tự dừng mà sẽ cùng chạy với cả các chương trình khác. Vậy DOS có phải là hệ điều hành đa nhiệm không"] = "Không";
questionAnswer["Khẳng định nào không chính xác"] = "-Hệ điều hành đa nhiệm (multi-task) là hệ điều hành đa người sử dụng (multi-user) \n-DOS là hệ điều hành phân chia thời gian";
questionAnswer["Cái tên nào sau đây không phải là một hệ điều hành?"] = "UPS";
questionAnswer["Trong chế độ phân trang, một chương trình được cấp một số trang nhớ, kích thước của các trang nhớ này ra sao?"] = "Bằng nhau.";
questionAnswer["Phần mềm Windows, Linux và OS2 có đặc điểm gì chung"] = "Tất cả đều là hệ điều hành";
questionAnswer["Cơ chế spooling cho phép"] = "Giảm thời gian kết thúc xử lý";
questionAnswer["Ý nào dưới đây là đúng: Hệ điều hành máy tính cá nhân"] = "là phần mềm phải có để máy tính cá nhân có thể hoạt động";
questionAnswer["Khẳng định nào sai. Các chức năng của hệ điều hành gồm có"] = "Quản lý giao tiếp với các máy tính khác qua các mạng để tránh virus lây lan";
questionAnswer["Khẳng định nào đúng nhất. Một hệ điều hành bất kỳ có thể"] = "Quản lý thiết bị , chương trình và dữ liệu trong quá trình làm việc và cung cấp môi trường giao tiếp giữa người sử dụng và máy tính";
questionAnswer["Khẳng định nào là sai khi nói về cơ chế plug & play. Tính năng plug & play là cơ chế của hệ điều hành nhằm"] = "Mặc dù trước đây đã cơ chế này đã được sử dụng khá thịnh hành cho các máy tính lớn (mini, mainframe) từ thập kỷ 80";
questionAnswer["Hệ điều hành thường được sử dụng với các máy tính lớn (mini, mainframe) thường là:"] = "UNIX";
questionAnswer["Mục đích của công việc định dạng đĩa là gì"] = "Tạo một đĩa trắng đúng khuôn dạng để lưu trữ dữ liệu";
questionAnswer["Khẳng định nào sai:"] = "Bộ nhớ ảo chỉ dùng với máy tính trước đây. Ngày nay, bộ nhớ trong đã rẻ và đủ lớn nên không cần dùng bộ nhớ ảo như trước nữa";
questionAnswer["Phát biểu nào sau đây là ĐÚNG"] = "GUI là viết tắt của Graphic User Interface.";
questionAnswer["Điều gì đúng khi nói về hệ điều hành đa nhiệm?"] = "Các chương trình được xử lý từng phần luân phiên (cùng tiến triển).";
questionAnswer["Chọn câu trả lời thích hợp nhất: “Tại sao phải định kì sử dụng công cụ chống phân mảnh đĩa cứng"] = "để tốc độ truy xuất dữ liệu từ đĩa cứng nhanh hơn";
questionAnswer["Bạn đã cài đặt một đĩa hoàn toàn mới và bạn muốn định dạng nó. Mục đích của công việc định dạng là gì"] = "Tạo một đĩa để đọc và chấp nhận dữ liệu";
questionAnswer["Trong những hệ điều hành sau, hệ nào không phải loại đa nhiệm (multitask)"] = "DOS";
questionAnswer["Hệ điều hành bắt đầu xuất hiện ở máy tính thế hệ nào"] = "2";
questionAnswer["Câu nào đúng khi nói về cơ chế plug & play của hệ điều hành?"] = "Khả năng phát hiện và cài đặt chương trình điều khiển thiết bị ngoại vi mới ở mức độ tự động hóa cao.";
questionAnswer["Trong cách hệ điều hành sau, hệ nào là đơn nhiệm"] = "DOS";
questionAnswer["Câu nào đúng khi nói về hệ điều hành DOS?"] = "Là hệ điều hành đơn chương trình.";
questionAnswer["Trong các máy tính ngày nay, có còn dùng cơ chế spooling nữa hay không"] = "Có";
questionAnswer["Lợi ích của GUI (Graphic User Interface) là gì"] = "GUI cho phép dùng con chuột để thao tác với máy tính";
questionAnswer["Trong cách hệ điều hành sau, hệ nào là đa người dùng"] = "Windows 2000";
questionAnswer["Trong những hệ điều hành sau, hệ nào là loại nhiều người dùng (multiuser)"] = "UNIX";
questionAnswer["Khẳng định nào là đúng khi nói về cơ chê plug & play. Tính năng plug & play là cơ chế của hệ điều hành nhằm"] = "Phát hiện ngoại vi mới để tự cài đặt chương trình điều khiển phù hợp và nếu không làm được thì cảnh báo người sử dụng";

questionAnswer["Hoạt động nào không thuộc công việc trong giai đoạn kiểm thử"] = "Kiểm thử mô hình";
questionAnswer["Hoạt động nào không hợp lý trong giai đoạn viết phần mềm"] = "Kiểm thử mô hình";
questionAnswer["Phần mềm là gì"] = "-Chương trình, cấu trúc dữ liệu và tài liệu \n-Là chương trình, cách tổ chức dữ liệu (cấu trúc dữ liệu) và tài liệu về chúng";
questionAnswer["Phần mềm nào trong số các phần mềm sau là phần mềm nhúng"] = "Từ một mạch có bộ vi xử lý điều khiển bảng quảng cáo";
questionAnswer["Ngôn ngữ lập trình là:"] = "-Phương tiện diễn đạt thuật tóan có thể sử dụng để máy tính thực hiện công việc \n-Là phương tiện diễn đạt các giải thuật có thể chuyển giao cho máy tính thực hiện";
questionAnswer["Câu nào chưa đúng trong số các câu sau?"] = "Phần mềm nguồn mở - Open source software: công bố một phần mã nguồn để mọi người tham gia phát triển";
questionAnswer["Chọn câu đúng và đầy đủ nhất về khái niệm phần mềm:"] = "Là chương trình, cách tổ chức dữ liệu (cấu trúc dữ liệu) và tài liệu về chúng";
questionAnswer["Chọn câu đúng và đầy đủ nhất về khái niệm phần mềm"] = "Là chương trình, cách tổ chức dữ liệu và tài liệu";
questionAnswer["Phần mềm nào sau đây có thể đọc các file định PDF?"] = "Foxit Reader.";
questionAnswer["Hệ điều hành là"] = "-Phần mềm hệ thống \n-Phần mềm quản lý các thiết bị, quản lý công việc xử lý, quản lý dữ liệu và thực hiện giao tiếp người - máy hoặc máy - máy";
questionAnswer["Theo bạn, các phần mềm sau thuộc nhóm phần mềm nào: MS Word, MS Excel, MS Access, MS PowerPoint, MS Internet Explorer"] = "Nhóm phần mềm ứng dụng";
questionAnswer["Bạn có thể đã biết phần mềm thi trắc nghiệm online. Trên màn hình sẽ có các câu hỏi với nhiều phương án lựa chọn. Người thi sẽ đánh dấu vào ô thích hợp. Khi hết thời gian người thi sẽ được công bố số điểm đã đạt được. Phần mềm này có được coi là phần mềm trí tuệ nhân tạo hay không"] = "Không";
questionAnswer["Đâu là một ví dụ về phần mềm máy tính"] = "Hệ điều hành";
questionAnswer["Khi ghi file trên đĩa, có cơ chế thu hồi các vùng đĩa khi xóa file và các vùng đĩa đó được phân phối lại cho các file khác. Điều này dẫn đến file có thể bị ghi trên nhiều vùng đĩa rời nhau làm việc truy cập file bị chậm. Trên Windows có phần mềm dồn đĩa (defragment), cho phép dồn các phân mảnh của file vào các vùng kế tiếp nhau để tăng hiệu quả truy cập đĩa. Phần mềm này là loại phần mềm nào."] = "Phần mềm tiện ích";
questionAnswer["Tại sao hàng năm luôn xuất hiện các phiên bản phần mềm mới? Nguyên nhân do"] = "Nhà sản xuất nâng cấp sản phẩm của mình.";
questionAnswer["Các phần mềm MS Word, MS Excel, MS Access, MS PowerPoint, MS Internet Explorer thuộc nhóm phần mềm nào?"] = "Nhóm phần mềm ứng dụng.";
questionAnswer["Phát biểu nào sau đây không đúng?"] = "Phần mềm ứng dụng bao gồm hệ điều hành, các chương trình điều khiển thiết bị...";
questionAnswer["Hoạt động thiết kế nào không thuộc công việc phát triển phần mềm"] = "Thiết kế mạng máy tính";
questionAnswer["Tuyên bố nào đúng"] = "MicroSoft C là một phần mềm phát triển";
questionAnswer["Hoạt động nào không thuộc công việc bảo trì"] = "Nâng cập thiết bị để tốc độ xử lý cao hơn";
questionAnswer["Một số phần mềm kiểm tra virus chạy trong chế độ thường trực. Mỗi khi chạy một chương trình lấy xuống từ Internet hay chạy một file bị nhiễm một loại virus nào đó nó liền dừng lại cảnh báo. Phần mềm này có được coi là phần mềm trí tuệ nhân tạo hay không"] = "Không";
questionAnswer["Hoạt động nào không thuộc công việc bảo trì phần mềm"] = "-Thay đổi mô hình toán học để thuật toán xử lý hiệu quả hơn \n-Nâng cấp hệ điều hành để phần mềm chạy ổ định hơn";
questionAnswer["Khi mua thiết bị ngoại vi cho máy tính, thường có các đĩa CD đi kèm chứa chương trình điều khiển thiết bị đó. Các chương trình điều khiển thiết bị thuộc loại phần mềm nào"] = "Phần mềm hệ thống";
questionAnswer["Chọn câu thích hợp để phân biệt giữa phần mềm ứng dụng và phần mềm hệ điều hành"] = "Phần mềm ứng dụng cần phần mềm hệ điều hành để chạy";
questionAnswer["Trình duyệt (Browser) dùng để truy nhập WEB là loại phần mềm nào"] = "Ứng dụng";
questionAnswer["Trong 4 phần mềm sau đây, phần mềm nào có thể thuộc loại tiện ích"] = "Sao lưu dữ liệu vào ổ đĩa cứng dự phòng";
questionAnswer["Phần mềm Windows, Linux và OS2 có đặc điểm gì chung"] = "Tất cả đều là hệ điều hành.";

questionAnswer["Mạng rộng là mạng"] = "-Hình thành từ việc liên kết các mạng cục bộ thông qua các thiết bị kết nối \n-Phải kết nối qua các hệ thống dẫn đường \n-Hình thành từ việc liên kết các mạng cục bộ hay các máy tính độc lập thông qua các các mạng viễn thông";
questionAnswer["Chuyển mạch (switch) khác bộ cắm nối tập trung HUB ở điểm nào"] = "Cắt lan truyền tín hiệu giữa các cổng khi không có nhu cầu nối giữa các cổng";
questionAnswer["Hãy cho câu trả lời đúng và đầy đủ nhất về mạng máy tính:"] = "Là tập các máy tính được nối với nhau theo các kênh truyền dữ liệu và tuân theo những quy ước truyền thông để các máy có thể hiểu các dữ liệu truyền cho nhau";
questionAnswer["Chọn câu trả lời đầy đủ nhất về mô hình cộng tác theo kiểu Client/Server :"] = "Các máy khách đưa ra yêu cầu, máy chủ xử lý và trả lại kết quả cho máy khách";
questionAnswer["Mạng WAN:"] = "Cho phép kết nối các mạng LAN nhỏ lại thành một mạng duy nhất.";
questionAnswer["Định nghĩa đúng nhất về mạng máy tính:"] = "Là tập các máy tính được nối với nhau theo các đường truyền vật lý và tuân theo một quy ước truyền thông.";
questionAnswer["Thiết bị cho phép cắm nối các dây cáp mạng của máy tính theo tô pô hình sao là loại nào"] = "Hub và Switch";
questionAnswer["Mạng máy tính là"] = "-Các máy tính được kết nối với nhau qua các kênh truyền tín hiệu vật lý để chia sẻ tài nguyên và liên lạc \n-Các máy tính được kết nối với nhau qua các kênh truyền tín hiệu vật lý để chia sẻ tài nguyên và thông tin.";
questionAnswer["Khẳng định nào đúng. Giao thức cảm nhận sóng mang đa truy nhập CSMA cho phép"] = "Các máy tính có thể tham gia truyền thông khi phát hiện thấy đường truyền rỗi";
questionAnswer["Trong các loại cáp truyền sau cáp truyền nào cho băng thông cao nhất"] = "Cáp quang";
questionAnswer["Thành phần/thiết bị nào sau đây không phải là thiết bị đầu-cuối?"] = "Cáp mạng.";
questionAnswer["Điểm nào sai khi so sánh hoạt động của cầu (bridge) và chuyển mạch (switch)"] = "Các gói tin chuyển từ cổng nọ sang cổng kia khi không thấy máy cần chuyển tin nằm trên cùng một cổng";
questionAnswer["Cáp nào đi với HUB để cắm nối theo tô pô hính sao"] = "Cáp xoắn";
questionAnswer["Mạng cục bộ là mạng"] = "Mạng trong phạm vi nhỏ, các máy chia sẻ trực tiếp đường truyền chung, không dùng thiết bị dẫn đường";
questionAnswer["Chọn phát biểu kém thuyết phục nhất trong các phát biểu sau"] = "Lý do quan trọng nhất cần nối mạng vì cần sử dụng chung các thiết bị phần cứng.";
questionAnswer["Trong danh sách dưới đây, đâu là thiết bị mạng?"] = "Hub";
questionAnswer["Trong các lý do cần có mạng máy tính, lý do nào thiếu cơ sở nhất"] = "Liên lạc";
questionAnswer["Mô hình client-server là mô hình xử lý"] = "-Máy chủ (server) cung cấp các dịch vụ theo yêu cầu từ máy tính khác gọi là máy trạm. Các máy trạm có thể xử lý phối hợp với các xử lý khác trên máy chủ. \n-Xử lý phân tán ở nhiều máy. Máy chủ cung cấp các dịch vụ theo yêu cầu từ máy tính khác gọi là máy trạm.";
questionAnswer["Khẳng định nào sai đối với giao thức mạng cục bộ CSMA/CD"] = "Các máy tính có thể tham gia truyền thông khi phát hiện thấy không quá một máy tính khác đang tham gia truyền thông";
questionAnswer["Dưới góc độ địa lý, mạng máy tính được phân loại thành:"] = "Mạng cục bộ, mạng diện rộng, mạng toàn cầu.";
questionAnswer["Cáp quang nào có khả năng truyền xa hơn"] = "Cáp quang đơn mode";
questionAnswer["Điều gì đúng khi nói về địa chỉ IPv4?"] = "Tất cả các đáp còn lại.";
questionAnswer["Thông số nào của cấu hình máy ảnh hưởng đến khả năng hoạt động đa nhiệm?"] = "Tất cả các đáp án còn lại.";
questionAnswer["Mô hình mạng ngang hàng peer-to-peer là mô hình xử lý mà"] = "Mọi máy đều có thể là máy chủ nếu trên đó cho phép chia sẻ thiết bị và dịch vụ cho các máy khác";
questionAnswer["Tốc độ truy cập mạng được xác định theo đơn vị"] = "kbps.";
questionAnswer["Điểm khác biệt quan trọng giữa bộ tập trung Hub và bộ chuyển mạch Switch là gì?"] = "Bộ chuyển mạch truyền tin theo đúng địa chỉ nhận chứ không lan tỏa như bộ tập trung.";
questionAnswer["Chức năng của bộ lặp (repeater) là gì"] = "Tiếp nhận dữ liệu, khôi phục tín hiệu để chống làm hỏng tín hiệu nhằm mở rộng quy mô địa lý của mạng";

questionAnswer["URL (Uniform Resource Locator) dùng để chỉ định cách thức liên hệ với các tài liệu ở các máy trên mạng Internet. URL chứa"] = "Cả “Giao thức ứng dụng”, “Địa chỉ máy trên mạng” và “Đường dẫn của file và tham số nếu gọi ứng dụng”";
questionAnswer["DNS (Domain name service) là giao thức để"] = "“Từ địa chỉ dưới dạng tên miền chuyển thành địa chỉ IP” và “Đọc địa chỉ cho dễ”";
questionAnswer["Định nghĩa nào chính xác nhất về mạng Internet về phương diện tin học"] = "Là mạng rộng có quy mô toàn cầu hoạt động dựa trên giao thức TCP/IP";
questionAnswer["Bạn nhận được một bức thư điện tử chứa tệp tin đính kèm mà bạn không nhận biết ra, bạn sẽ xử lý thế nào trong tình huống này để đảm bảo an toàn?"] = "Quét tập tin này bằng chương trình chống virus";
questionAnswer["Lợi thế của mua hàng trực tuyến so với mua hàng bình thường ở cửa hàng là gì?"] = "Có thể mua hàng trong suốt 24h trong một ngày.";
questionAnswer["Dịch vụ nào phổ biến nhất trên Internet hiện nay"] = "WWW";
questionAnswer["Internet là"] = "Mạng rộng";
questionAnswer["Khi nói về ưu điểm của làm việc từ xa (Tele-working), ý nào sau đây không đúng?"] = "Tăng cường sự liên hệ trực tiếp";
questionAnswer["Trong các thể hiện sau đây, thể hiện nào không phải là một địa chỉ IP"] = "168.315.29.123";
questionAnswer["Địa chỉ 172.16.3.63 là địa chỉ"] = "Lớp B";
questionAnswer["Máy tính cung cấp các dịch vụ cho các máy tính cá nhân gọi là"] = "Server (máy chủ)";
questionAnswer["Thuật ngữ “Thương mại điện tử” nghĩa là"] = "Mua và bán hàng qua mạng máy tính Internet.";
questionAnswer["Dịch vụ nào cho phép sử dụng máy tính từ xa"] = "Telnet";
questionAnswer["Email là viết tắt của"] = "Electronic Mail";
questionAnswer["Người ta nói Internet là mạng chạy theo giao thức TCP/IP. Giao thức IP (Internet Protocol) liên quan tới"] = "Cả “Cơ chế định địa chỉ cho các máy tham gia mạng” và “Cơ chế dẫn đường cho các gói tin thông qua các máy dẫn đường (router)”";
questionAnswer["Thuật ngữ kỹ thuật trong mua và bán hàng qua mạng Internet là gì"] = "Thương mại điện tử (E-commerce)";
questionAnswer["Trong các đáp án sau, đáp án nào không thể là một địa chỉ IP :"] = "34.2.264.12";
questionAnswer["Từ trình duyệt trong phần URL một người gõ vào dòng sau http://vnu.edu.vn/uet/index.htm. Người này chờ kết quả nào"] = "Mở trang WEB index.htm trong đường dẫn uet của máy chủ có tên là vnu.edu.vn";
questionAnswer["Trong các thể hiện sau đây, cái nào không phải là một địa chỉ IP"] = "168.315.29.123";
questionAnswer["Diễn đàn (forum) khác với thư điện tử (Email) ở chỗ nào"] = "-Đối tượng nhận tin được người gửi chỉ định trước \n-Bạn phải chỉ định đối tượng nhận tin";
questionAnswer["Địa chỉ 192.168.3.63 là địa chỉ"] = "Lớp C";
questionAnswer["Máy tính nối và cung cấp các dịch vụ cho các máy PC khác gọi là"] = "Server (máy chủ)";

questionAnswer["Vấn đề sức khỏe phổ biến của người sử dụng máy tính là các chấn thương cổ tay. Nguyên nhân của chấn thương thông thường là gì?"] = "Sử dụng bàn phím lâu.";
questionAnswer["Câu nào dưới đây không đúng"] = "Vi rút máy tính lây nhiễm qua dùng chung máy tính";
questionAnswer["Trong những tình huống hoặc lĩnh vực nào sau đây, con người làm việc tốt hơn máy tính"] = "Nhận dạng.";
questionAnswer["Khi sử dụng hồ sơ điện tử thay cho hồ sơ giấy, ví dụ như bảng các câu hỏi trực tuyến. Bạn thấy ưu điểm nào sau đây nổi bật nhất?"] = "Việc tiêu thụ giấy giảm.";
questionAnswer["Quyền tác giả bao gồm quyền nhân thân và quyền sở hữu. Điều nào sau đây không phải quyền nhân thân:"] = "Hủy bỏ tác phẩm, tuyên bố không chịu trách nhiệm về mọi quyền lợi, nghĩa vụ và không cho phép ai được sử dụng.";
questionAnswer["Điều nào không phải là tấn công từ chối dịch vụ"] = "Tạo virus ở các máy của người truy cập để ngăn chặn việc truy cập tới dịch vụ";
questionAnswer["Điểm nào không phải là hành vi tấn công từ chối dịch vụ (Denial of service attack)"] = "Tấn công các thiết bị đảm bảo cho hoạt động của máy chủ dịch vụ để khi các thiết bị này bị khống chế thì máy chủ không còn an toàn nữa.";
questionAnswer["Điều gì mà tất cả các Virus máy tính đều có thể thực hiện?"] = "Tự nhân bản.";
questionAnswer["Nếu một máy tính bị nghi ngờ là nhiễm virus thì cách thức tốt nhất để kiểm tra và diệt virus là gì?"] = "Cài đặt một chương trình chống virus, quét virus các ổ đĩa của máy tính và cho chương trình này loại bỏ virus.";
questionAnswer["Ai không phải là tác giả của phần mềm"] = "Người không làm nhưng mua quyền sở hữu phần mềm";
questionAnswer["Một người mua một bản (licence) một phần mềm nào đó nhưng anh ta có hai máy tính. Nếu anh ta cài trên cả hai máy chỉ cho chính bản thân dùng. Theo thông lệ quốc tế, việc đó có là bất hợp pháp không"] = "Không";
questionAnswer["Điều nào sai"] = "Tác giả có thể cho phép người khác đứng tên tác giả";
questionAnswer["Tại sao không nên sao chép một trò chơi từ đĩa CDROM mà không được sự cho phép của người/tổ chức sở hữu trò chơi này?"] = "Bởi vì đó là vi phạm bản quyền.";
questionAnswer["Thư rác (spamming) là gì"] = "Gửi thư quảng cáo hoặc thông báo với một số lượng lớn không được sự đồng ý trước của người nhận";
questionAnswer["Virus máy tính"] = "Là một chương trình máy tính.";
questionAnswer["Một công ty sử dụng phần mềm mã nguồn mở cho khách hàng của mình. Ứng xử nào của công ty là hợp lý"] = "Được thu tiên đối với những phát triển thêm và công dịch vụ";
questionAnswer["Lời khuyên khi sử dụng mật khẩu máy tính là:"] = "Không bao giờ cho người khác biết mật khẩu của bạn.";
questionAnswer["Đâu là một ví dụ của chính sách mật khẩu tốt"] = "Không bao giờ cho người khác biết mật khẩu của bạn";
questionAnswer["Tấn công từ chối dịch vụ là gì"] = "Gửi thông báo nhiều đến mức làm hệ thống tê liệt vì quá tải";
questionAnswer["Cơ chế lây của virus file là gì"] = "Gây nhiễm vào một file nào đó, khi thi hành, nó sẽ chiếm quyền ghi file của hệ điều hành để sau đó mỗi khi chạy một ứng dụng nào đó, file ứng dụng đó được ghép thêm mã của virus";
questionAnswer["Đâu là điểm giống nhau giữa Virus và Worm"] = "Có cơ chế để lây nhiễm";
questionAnswer["Tại sao không nên sao chép một trò chơi CD Rom mà bạn không có giấy đăng ký bản quyền"] = "Bởi vì đó là vi phạm bản quyền";
questionAnswer["Điều nào là không đúng trong các cơ chế phát tán của sâu (worm)"] = "-Tạo ra các link để bẫy người dùng nạp về \n-Chương trình gây nhiễm tự tìm địa chi mail có trong hộp thư để gửi theo email dưới dạng các file đính kèm có hình thức thuận lợi để người nhận thư mở nó";
questionAnswer["Công ty X mua một chương trình máy tính, chương trình này sẽ được cài đặt miễn phí trong nội bộ công ty trong trường hợp:"] = "Khi bản quyền phần mềm cho phép điều này.";
questionAnswer["Trong công việc nào dưới đây, con người làm việc tốt hơn máy tính"] = "Nhận dạng các sự vật";
questionAnswer["Cơ chế lây của virus boot là gì"] = "Gây nhiễm trong đoạn mã khởi động của đĩa";
questionAnswer["Mục đích chủ yếu của chính sách an ninh thông tin của một tổ chức là gì"] = "Theo dõi và kiểm soát thông tin, dữ liệu nhạy cảm";
questionAnswer["Một người bật công tắc máy tính thấy máy không chạy gì cả, màn hình hiện ra các thông báo kiểm tra bộ nhớ tốt, sau đó màn hình chuyển sang tối om. Bật tắt công tắc máy tính nhiều lần, vẫn như vậy. Đèn trong phòng vẫn sáng. Điều gì có khả năng nhất"] = "Máy bị virus hay hỏng đĩa khởi động";
questionAnswer["Quyền tác giả bao gồm quyền nhân thân và quyền sở hữu. Điều nào sau đây không phải quyền sở hữu đối với phần mềm máy tính:"] = "Công bố phần mềm";
questionAnswer["4 điểm dưới đây là tính năng của vius. Điểm nào là điểm khác nhau giữa virus máy tính và sâu máy tính (computer worm)"] = "Phải sống nhờ vật chủ như file hay vùng thông tin hệ thống của đĩa và tự thi hành để nhân bản";
questionAnswer["X và Y trước đây cùng phát triển một phần mềm do X là người chủ trì. Sau nay hai người lập ra hai công ty khác nhau nhưng Y đăng ký bản quyền trước. Khi đó Y có vi phạm bản quyền không"] = "Không";
questionAnswer["Điều nào sai khi nói về các đặc điểm của phần mềm virus."] = "Virus chỉ hoạt động trên hệ điều hành Windows";
questionAnswer["Trong những công việc dưới đây, công việc nào con người làm tốt hơn máy tính"] = "Nhận dạng các sự vật.";
questionAnswer["Tại sao máy tính xách tay có thể gây rủi ro cho an ninh của công ty?"] = "Bởi vì những người không được phép có thể đọc được những thông tin mật nếu máy tính bị lấy cắp.";
questionAnswer["Hoạt động nào không phải là của Trojan"] = "Xóa các file dữ liệu của người dùng";
questionAnswer["Khẳng định nào dưới đây là sai:"] = "cài đặt phần mềm, trò chơi bị bẻ khoá là vi phạm luật bản quyền";
questionAnswer["Khi một cơ quan mua một chương trình máy tính, Trong những trường hợp nào chương trình này có thể được cài đặt miễn phí nội trong cơ quan đó"] = "Khi có sự đồng ý bản quyền cho phép điều này.";

questionAnswer["Thiết bị lưu trữ nào sau đây có thời gian truy cập nhanh nhất"] = "đĩa cứng";
questionAnswer["Các bản mạch cắm qua các khe cắm mở rộng có phải là thiết bị vào hoặc ra hay không"] = "Còn tuỳ từng trường hợp cụ thể";
questionAnswer["Chức năng của đồng hồ (clock) là gì?"] = "Tạo các xung điện áp chính xác, đều đặn để sinh các tín hiệu cơ bản để điều chế thông tin và đồng bộ hóa các thành phần của máy tính.";
questionAnswer["Các sinh viên  phát biểu: nguyên lý Von Neumann nói rằng"] = "Sv3 và Sv4";
questionAnswer["Ổ đĩa cứng là thiết bị"] = "Cả vào và ra";
questionAnswer["Sau một thời gian sử dụng máy tính, bạn cảm thấy máy tính chạy chậm hơn nhiều, đặc biệt khi mở nhiều chương trình ứng dụng một lúc. Nguyên nhân nào dưới đây là có khả năng cao nhất"] = "Không gian trống trong đĩa cứng quá ít";
questionAnswer["Có thể ghi vào bộ nhớ ROM được không"] = "Có một số loại ROM ghi được bằng các phương tiện chuyên dụng";
questionAnswer["Ở siêu thị người ta dùng đầu đọc mã vạch để nhận mã hàng hoá. Đó có phải là thiết bị vào của máy tính hay không"] = "Có";
questionAnswer["Bàn phím là thiết bị"] = "Vào";
questionAnswer["Trong thứ tự kiểu little-endian, byte có ý nghĩa thấp hơn được đặt trước byte có ý nghĩa cao hơn, ví dụ số thập lục phân 0x1234 có thứ tự lưu 2 byte là [0x34, 0x12]. Hỏi trạng thái của các bit khi lưu từ nhị phân 1010.0111.1111.0001 là?"] = "1111.0001.1010.0111.";
questionAnswer["Trên đĩa từ, các bít được thể hiện bằng các vùng có chiều từ thông khác nhau, một chiều cho bít 0, chiều ngược lại cho bit 1. Điều đó đúng hay sai"] = "Sai";
questionAnswer["Bộ nhớ ROM được dùng để"] = "Ghi nhớ chương trình và dữ liệu sẵn sàng để làm việc mà không phải nạp lại";
questionAnswer["Đâu là thiết bị nhập dữ liệu?"] = "Máy quét (scan) và đầu đọc mã vạch.";
questionAnswer["CPU là thiết bị"] = "Không phải thiết bị ngoại vi";
questionAnswer["Máy in là thiết bị"] = "Ra.";
questionAnswer["RAM là viết tắt của"] = "Random Access Memory.";
questionAnswer["Trong những năm gần đây, xuất hiện bộ nhớ flash cắm rời theo đường USB. Đây là bộ nhớ bán dẫn nhưng vẫn được coi là bộ nhớ ngoài. Theo bạn thì lý do nào sau đây là xác đáng nhất."] = "Không tương tác trực tiếp với bộ xử lý và nội dung không bị xoá khi không có nguồn";
questionAnswer["Ổ đĩa CDROM là thiết bị"] = "Ra";
questionAnswer["Trong lĩnh vực máy tính, chữ viết tắt “MB” thường được dùng để đo lường giá trị gì?"] = "Khả năng lưu trữ.";
questionAnswer["Đĩa được gọi là bộ nhớ ngoài truy nhập trực tiếp (direct access) vì lý do"] = "Có thể tính trước địa chỉ vùng dữ liệu cần đọc để đặt đầu đọc (đầu từ) trực tiếp vào vùng dữ liệu";
questionAnswer["Máy in là thiết bị:"] = "Ra";
questionAnswer["Lý do đúng đắn nhất phân biệt thiết bị thuộc khu vực ngoại vi và thiết bị thuộc khu vực trung tâm của máy tính là:"] = "Thiết bị ở khu vực trung tâm được dùng để xử lý dữ liệu còn thiết bị ở khu vực ngoại vi là trao đổi dữ liệu giữa máy tính và môi trường tính toán";
questionAnswer["Cái gì của ô nhớ có thể thay đổi được?"] = "Nội dung.";
questionAnswer["Cổng nào sau đây là cổng kết nối giữa màn hình và máy tính?"] = "VGA";
questionAnswer["Chọn câu trả lời ĐÚNG nhất: USB là"] = "Thiết bị lưu trữ ngoài.";
questionAnswer["Con số 20GB trong hệ thống máy tính có nghĩa là"] = "Ổ đĩa cứng có dung lượng là 20GB.";
questionAnswer["RAM thuộc khối thiết bị:"] = "Memory (bộ nhớ).";
questionAnswer["Loại máy tính nào thường đắt nhất"] = "Máy chủ";
questionAnswer["Con số 3GB trong hệ thống máy tính có nghĩa là:"] = "Bộ nhớ RAM hoặc ổ đĩa cứng có dung lượng là 3GB.";
questionAnswer["Cách trả lời đúng nhất về nguyên lý truy nhập theo địa chỉ"] = "Chương trình chỉ định dữ liệu thông qua địa chỉ của dữ liệu trong bộ nhớ chứ không theo giá trị của dữ liệu";
questionAnswer["Trong các lý do dùng bộ nhớ ROM sau đây, lý do nào xác đáng nhất"] = "Nhớ được thông tin không cần nguồn điện và không ghi lại được bằng cách ghi thông thường nên thường được dùng ghi các chương trình điền khiển và các tham số hoạt động cơ sở của máy.";
questionAnswer["CPU là viết tắt của"] = "Central Processing Unit";
questionAnswer["Đơn vị đo độ sáng của thiết bị máy chiếu là:"] = "Lumens";
questionAnswer["Tốc độ đồng hồ của máy tính đuợc tính theo"] = "hertz và các bội của nó";
questionAnswer["Thông số \"7200 rpm\" là của thiết bị nào?"] = "HDD.";
questionAnswer["Trong các thiết bị sau, thiết bị nào có thời gian truy xuất dữ liệu chậm nhất"] = "Đĩa mềm";
questionAnswer["Điều nào là sai khi nói về chức năng của CPU"] = "-Xuất nhập dữ liêu với các thiết bị ngoại vi \n-Trao đổi dữ liệu trực tiếp với bộ nhớ ngoài";
questionAnswer["Có thể ghi vào bộ nhớ EPROM được không"] = "Không thể ghi được bằng máy tính, có thể ghi bằng các phương tiện khác";
questionAnswer["Chọn câu trả lời chính xác nhất về chức năng của CPU"] = "Điều khiển, phối hợp các thiết bị để máy tính thực hiện đúng chương trình đã định";
questionAnswer["Modem là thiết bị"] = "Cả vào và ra";
questionAnswer["Độ phân giải của màn hình thể hiện bởi"] = "Kích thước của màn hình";
questionAnswer["Chuột là thiết bị"] = "Vào";
questionAnswer["Màn hình cảm ứng là thiết bị gì của máy tính?"] = "Thiết bị vào và ra.";
questionAnswer["Thiết bị sử dụng pin để cung cấp điện liên tục cho hệ thống ngay cả khi điện lưới bị cắt được gọi là?"] = "UPS";
questionAnswer["Màn hình máy tính (màn hình không cảm ứng) là thiết bị"] = "Ra.";
questionAnswer["Loại phím nào trên bàn phím mà chức năng của nó được xác định tùy thuộc vào các phần mềm cụ thể?"] = "Phím chức năng.";
questionAnswer["Đâu là thứ tự sắp xếp đúng tốc độ truy cập tăng dần của các bộ nhớ?"] = "Flash USB, Ổ đĩa cứng, RAM, CPU Cache.";
questionAnswer["Khi mất điện đột ngột, dữ liệu lưu trữ trong thiết bị nào dưới đây sẽ mất?"] = "RAM";
questionAnswer["Lý do đúng đắn nhất phân biệt thiết bị thuộc khu vực ngoại vi là:"] = "Thiết bị ở khu vực ngoại vi có chức năng trao đổi dữ liệu giữa máy tính và môi trường tính toán còn thiết bị ở khu vực trung tâm được dùng để xử lý dữ liệu";
questionAnswer["Bộ nhớ được chia thành 2 loại là những loại nào?"] = "Bộ nhớ trong và bộ nhớ ngoài.";
questionAnswer["Ổ cứng là"] = "Thiết bị lưu trữ ngoài.";
questionAnswer["Tốc độ truyền dữ liệu tối đa trên lý thuyết của USB 2.0 là"] = "480 Mbps.";
questionAnswer["Câu trả lời đúng nhất cho chức năng của bộ nhớ RAM:"] = "Ghi nhớ dữ liệu và chương trình trong thời gian máy làm việc";
questionAnswer["Loại phím nào trên bàn phím mà tác dụng của nó được xác định tuỳ thuộc vào các phần mềm cụ thể:"] = "Phím chức năng";
questionAnswer["Khi bật máy tính, thiết bị nào sau đây được dùng để lưu trữ các chương trình ban đầu phục vụ cho việc khởi động máy?"] = "ROM";
questionAnswer["Nhìn vào các tham số cấu hình của một máy tính: 1.8GHz, 20GB, 1GB con số 20GB là thông số gì?"] = "Dung lượng của ổ đĩa cứng.";
questionAnswer["Vật nào không phải thiết bị vào của máy tính?"] = "Màn hình không cảm ứng.";
questionAnswer["Thông số \"Core i3, socket 775\" là của thiết bị nào?"] = "CPU.";
questionAnswer["Chọn câu trả lời đúng nhất: Đĩa cứng là"] = "Thiết bị lưu trữ ngoài";
questionAnswer["So sánh những một máy tính điện tử (computer) với một máy tính cầm tay dùng để tính các phép tính số học cộng trừ nhân chia (calculator), trừ những điểm khác nhau như khả năng thực hiện chương trình hay kích thước thì có nhiều điểm mà một người nghĩ là giống nhau. Điều nào sai"] = "Cùng có bộ điều khiển";
questionAnswer["Một sinh viên đưa ra những điểm tương đồng giữa một máy vi tính (mico computer) với một máy tính bỏ túi (calculator). Điều nào sai"] = "Đều có CPU";
questionAnswer["Các sinh viên tranh luận về lý do dùng bộ nhớ ngoài"] = "Ý kiến 1 và ý kiến 2";
questionAnswer["Đọc các thông số cấu hình của một máy tính thông thường: 2GHz - 20GB - 256MB, bạn cho biết con số 256MB chỉ điều gì"] = "Chỉ dung lượng của bộ nhớ truy cập ngẫu nhiên RAM";
questionAnswer["Ba thiết bị đầu vào phổ biến gồm những gì?"] = "Bàn phím, chuột, Microphone.";
questionAnswer["Cách trả lời đúng nhất về nguyên lý điều khiển theo chương trình"] = "Máy tính chỉ hoạt động theo các chỉ dẫn của chương trình được nạp vào trong bộ nhớ";
questionAnswer["Một người bật công tắc máy tính thấy máy không chạy gì cả, màn hình tối om, không nghe thấy tiếng quạt làm nguội máy. Bật tắt công tắc máy tính nhiều lần, vẫn như vậy. Đèn trong phòng vẫn sáng. Điều gì có khả năng nhất"] = "Máy không cắm điện";
questionAnswer["Bạn đã cài đặt một bộ xử lý mới có tốc độ đồng hồ cao hơn vào máy của bạn. Điều này có thể có kết quả gì"] = "Máy tính của bạn sẽ chạy nhanh hơn";
questionAnswer["Thiết bị nào sau đây là phương tiện lưu trữ quang học?"] = "DVD-R";
questionAnswer["Nếu sắp theo thứ tự từ khả năng lưu trữ từ cao đến thấp, bạn chọn phương án nào trong số các phương án sau:"] = "Đĩa cứng - đĩa DVD - đĩa CD - đĩa mềm";
questionAnswer["CPU là"] = "Central Processing Unit.";
questionAnswer["Điều nào là nguyên lý Von Neumann"] = "Dữ liệu được xác định qua địa chỉ trong bộ nhớ và để xử lý máy tính được điều khiển theo chương trình nạp vào trong bộ nhớ";
questionAnswer["Chọn phát biểu SAI về CPU trong các phát biểu sau:"] = "Là hộp máy của máy vi tính, trong đó có bộ số học - lôgic và bộ nhớ.";
questionAnswer["Bộ nhớ trong là thiết bị"] = "Không phải thiết bị ngoại vi";
questionAnswer["Modem là thiết bị dùng để:"] = "Chuyển đổi tín hiệu số của máy tính sang dạng tín hiệu tương tự để truyền được trên đường điện thoại.";
questionAnswer["Lý do phân biệt thiết bị thuộc khu vực ngoại vi và thiết bị thuộc khu vực trung tâm của máy tính là"] = "Thiết bị ở khu vực trung tâm được dùng để xử lý dữ liệu còn thiết bị ở khu vực ngoại vi là trao đổi dữ liệu giữa máy tính và môi trường tính toán";
questionAnswer["Màn hình là thiết bị loại nào:"] = "Ra";

questionAnswer["Để mã hóa 16,7 triệu màu rời rạc thì cần dùng ít nhất bao nhiêu bit?"] = "24.";
questionAnswer["Ngoài định nghĩa đúng “dữ liệu là hình thức thể hiện của thông tin trong mục đích lưu trữ, truyền và xử lý thông tin”, còn có các định nghĩa khác nữa. Trong các định nghĩa sau đây, xét về bản chất định nghĩa nào có thể chấp nhận được về dữ liệu"] = "Là đối tượng xử lý của máy tính";
questionAnswer["Điều nào sai khi nói về xử lý thông tin là"] = "Tăng thêm lượng tin để tăng hiểu biết";
questionAnswer["Bảng chữ cái của mã hóa lục thập phân cần bao nhiêu kí tự khác nhau?"] = "60.";
questionAnswer["Độ dài là thông tin"] = "Liên tục";
questionAnswer["Số nhị phân là gì?"] = "Các số 1 và 0.";
questionAnswer["4 KB bằng bao nhiêu bit?"] = "32768.";
questionAnswer["Chọn câu đúng và đầy đủ nhất trong định nghĩa về byte sau đây"] = "Là một đại lượng đo thông tin bằng 8 bit";
questionAnswer["Trong những điều sau đây nói về về Kilobyte (KB), điều nào đúng"] = "Đơn vị đo lượng tin lớn hơn 1000 byte";
questionAnswer["Có một tập hợp gồm 500 đối tượng. Trong mã hoá nhị phân cần bao nhiêu bít để có thể mã hoá được các đối tượng của tập hợp này"] = "9";
questionAnswer["Trong định nghĩa CNTT trong bộ luật CNTT của Việt nam có nói: \"Công nghệ thông tin là tập hợp các các phương pháp khoa học, công nghệ và công cụ kỹ thuật hiện đại để sản xuất, truyền, thu thập, xử lý, lưu trữ và trao đổi thông tin số.\". Bạn hiểu thế nào là thông tin số"] = "Là các thông tin được mã hoá dưới dạng số";
questionAnswer["Đơn vị đo lượng tin là"] = "bit";
questionAnswer["Trong sản xuất phần cứng, để phù hợp với suy nghĩ của người tiêu dùng, nhà sản xuất định nghĩa theo hệ thập phân, 1 KB = 1000 B, 1 MB = 1000 KB, 1 GB = 1000 MB. Như vậy nếu một nhà sản xuất ổ đĩa cứng ghi trên vỏ là 1 TB thì thực tế có bao nhiêu GB?"] = "909.49.";
questionAnswer["Cần bao nhiêu bít để mã hoá các trạng thái của một con xúc sắc 6 mặt"] = "3";
questionAnswer["Thông tin là gì?"] = "Là tất cả những gì mang lại cho con người hiểu biết.";
questionAnswer["Nếu dùng mã có độ dài 5 kí tự trong mã hóa nhị phân thì có thể tạo ra bao nhiêu mã khác nhau?"] = "32.";
questionAnswer["Chọn phương án đúng nhất khi nói về bit:"] = "Là đơn vị thông tin";
questionAnswer["Dữ liệu là"] = "Là hình thức thể hiện của thông tin trong mục đích lưu trữ, truyền và xử lý thông tin";
questionAnswer["Phương án trả lời nào đúng nhất cho giá mang tin là"] = "Tất cả các phương tiện có thể lưu trữ thông tin";
questionAnswer["Một bức ảnh có kích thước 1920 x 1080 điểm ảnh, mỗi điểm ảnh cần dùng 24 bit để biểu diễn. Giả sử bức ảnh đó được nén bằng thuật toán JPEG giúp giảm dung lượng đi 10 lần. Hỏi ảnh sau khi nén có dung lượng khoảng bao nhiêu KB?"] = "622.";
questionAnswer["Trong sản xuất phần cứng, để phù hợp với suy nghĩ của người tiêu dùng, nhà sản xuất định nghĩa theo hệ thập phân, 1 KB = 1000 B, 1 MB = 1000 KB, 1 GB = 1000 MB. Như vậy nếu một nhà sản xuất RAM ghi trên vỏ là 8 GB thì thực tế có bao nhiêu GB?"] = "7.45.";
questionAnswer["Đơn vị nào tương đương với 1024 MB?"] = "GB.";
questionAnswer["Tín hiệu là"] = "Hình thức vật lý của thông tin";
questionAnswer["Định nghĩa nào đúng nhất về dữ liệu:"] = "-Là đối tượng xử lý của máy tính \n-Là hình thức thể hiện của thông tin trong mục đích lưu trữ, truyền và xử lý thông tin";
questionAnswer["Chọn ra định nghĩa đúng cho tín hiệu."] = "Tín hiệu là hình thức vật lý của thông tin.";
questionAnswer["Trong sản xuất phần cứng, để phù hợp với suy nghĩ của người tiêu dùng, nhà sản xuất định nghĩa theo hệ thập phân, 1 KB = 1000 B, 1 MB = 1000 KB, 1 GB = 1000 MB. Như vậy nếu một nhà sản xuất RAM ghi trên vỏ là 16 GB thì thực tế có bao nhiêu GB?"] = "14.90.";
questionAnswer["Chọn câu đúng?"] = "Ảnh bit map lưu trữ từng điểm ảnh.";
questionAnswer["Định nghĩa nào xác đáng nhất về Công nghệ thông tin"] = "Là tập hợp các phương pháp khoa học, công nghệ và công cụ kỹ thuật hiện đại để sản xuất, truyền, thu thập, xử lý, lưu trữ và trao đổi thông tin số.";
questionAnswer["Chữ viết tắt MB thường gặp trong các tài liệu về máy tính có nghĩa là gì:"] = "là đơn vị đo khả năng lưu trữ";
questionAnswer["Chọn định nghĩa chính xác nhất về thông tin"] = "Là tất cả những gì mang lại cho con người hiểu biết";
questionAnswer["Cùng một tín hiệu trong những hoàn cảnh khác nhau có thể chuyển tải các thông tin khác nhau"] = "Đúng";
questionAnswer["1 kilobyte bằng:"] = "1024 byte";
questionAnswer["Để mã hóa một bức ảnh có 256 điểm ảnh cần dùng ít nhất bao nhiêu kilobyte biết mỗi điểm ảnh cần dùng 16 byte?"] = "4 .";
questionAnswer["Có thể thể hiện thông tin bằng nhiều hình thức khác nhau hay không"] = "Có";
questionAnswer["Người và máy tính giao tiếp thông qua:"] = "Bàn phím và màn hình";
questionAnswer["Điều nào đúng trong các khẳng định sau:"] = "Thông tin rời rạc có thể mã hoá được bằng bộ chữ hữu hạn";
questionAnswer["Một bit là"] = "Là đơn vị thông tin";
questionAnswer["Nếu dùng mã có độ dài 3 kí tự trong mã hóa bát phân thì có thể tạo ra bao nhiêu mã khác nhau?"] = "512.";
questionAnswer["Điện áp là thông tin"] = "Liên tục";
questionAnswer["1 byte bằng:"] = "8 bit";
questionAnswer["Định nghĩa nào đúng nhất về đơn vị Byte"] = "Là lượng tin 8 bít";
questionAnswer["Chọn câu chính xác nhất trong định nghĩa về bit sau đây"] = "Là đơn vị thông tin có thể thể hiện qua một chữ số nhị phân trong một mã hoá nhị phân";
questionAnswer["Tin học là gì?"] = "Khoa học xử lý thông tin tự động dựa trên máy tính điện tử";
questionAnswer["Nhiều tín hiệu khác nhau có thể chuyển tải một nội dung thông tin"] = "Đúng";
questionAnswer["Có người đưa ra các lý do sử dụng hệ đếm nhị phân với máy tính. Trong các lý do sau, lý do nào kém thuyết phục nhất"] = "Hệ đếm cơ số 2 là hệ đếm có cơ số nhỏ nhất";
questionAnswer["Danh sách học sinh của một lớp là thông tin"] = "Rời rạc";
questionAnswer["Đơn vị đo lượng thông tin là"] = "Bit";
questionAnswer["Chọn ra đặc điểm đúng cho thông tin liên tục."] = "Cả \"Lượng giá trị của thông tin liên tục là vô hạn.\" và \"Có thể dùng mã hóa rời rạc để biểu diễn gần đúng thông tin liên tục.\".";
questionAnswer["Một tệp âm thanh có kích thước 2 MB khi nén với định dạng MP3, nó giảm kích thước đi 11 lần. Hỏi kích thước của tệp tin nén khoảng bao nhiêu KB?"] = "186.";
questionAnswer["Thông tin liên tục có thể mã hoá bằng một bảng chữ hữu hạn được không"] = "Không được";

questionAnswer["Biểu diễn hệ 16 của số nhị phân 10011011110 là"] = "4DE";
questionAnswer["Kết quả nào đúng khi đổi 100001001 từ hệ 2 sang 10"] = "265";
questionAnswer["Chọn câu trả lời đúng và đầy đủ nhất về dạng nhị phân của số thập phân 0.65 là (nhóm số đặt trong hai dấu ngoặc đơn là nhóm tuần hoàn vô hạn):"] = "0.10(1001)";
questionAnswer["Kết quả nào đúng khi đổi 3579 từ 10 sang 16"] = "DFB";
questionAnswer["Kết quả nào là đúng khi đổi số thập phân 87 ra hệ nhị phân"] = "1010111";
questionAnswer["Kết quả nào đúng khi đổi 101000101100 từ hệ 2 sang 16"] = "A2C";
questionAnswer["Kết quả nào đúng khi đổi 100111010 từ hệ 2 sang 10"] = "314";
questionAnswer["Kết quả nào đúng khi đổi 1111000001 từ hệ 2 sang 16"] = "3C1";
questionAnswer["Kết quả phép nhân hai số nhị phân 1100 x 100001 đổi sang hệ đếm cơ số 16 là bao nhiêu"] = "18C";
questionAnswer["Kết quả nào là đúng khi đổi số nhị phân 101011 sang số thập phân"] = "43";
questionAnswer["Kết quả nào là đúng khi đổi số thập phân 0.423 ra hệ nhị phân lấy đến 6 chữ số lẻ"] = "0.011011";
questionAnswer["Kết quả nào đúng khi đổi ABC từ hệ 16 sang hệ 10"] = "2748";
questionAnswer["Đặc điểm nào đúng cho biểu diễn số dấu phẩy động?"] = "Là \"Bít đầu tiên để mã dấu của số\" và \"Số bít cho phần định trị và phần bậc là cố định.\"";
questionAnswer["Biểu diễn nào là biểu diễn đúng của số 7E9 trong hệ nhị phân"] = "11111101001";
questionAnswer["Số 13 có biểu diễn nhị phân là gì?"] = "1101.";
questionAnswer["Kết quả nào là đúng khi đổi số thập phân 0.125 ra hệ nhị phân lấy đến 4 chữ số lẻ"] = "0.0010";
questionAnswer["Kết quả nào đúng khi đổi 3781 từ hệ đếm cơ số 10 sang hệ đếm cơ số 2"] = "111011000101";
questionAnswer["Biểu diễn số nhị phân 1011 0111101 trong hệ 16 là:"] = "5BD";
questionAnswer["Kết quả nào là đúng khi đổi số Hexa 2A3 ra hệ thập phân"] = "675";
questionAnswer["Kết quả nào đúng khi đổi 314 từ hệ đếm cơ số 10 sang hệ đếm cơ số 2"] = "100111010";
questionAnswer["Có bao nhiêu hàm đại số logic ba ngôi?"] = "256.";
questionAnswer["Cho phép toán A xác định như sau 0 A 0 = 0, 1 A 0 = 0, 0 A 1 = 1, 1 A 1 = 0, hỏi A có thể biểu diễn qua phép hội (AND) ^ và phép phủ định ¬ (NOT) như thế nào?"] = "a A b = (¬a) ^ b.";
questionAnswer["Các sinh viên tranh luận:"] = "Sv1, Sv3 và Sv4";
questionAnswer["Cho phép toán A xác định như sau 0 A 0 = 0, 1 A 0 = 1, 0 A 1 = 1, 1 A 1 = 0, hỏi kết quả của phép tính 0101 A 1010 bằng bao nhiêu?"] = "1111.";
questionAnswer["Kí hiệu ≡ được hiểu là đồng nhất, nghĩa là bằng nhau trong mọi trường hợp. Khẳng định nào dưới đây không đúng?"] = "¬((¬x v y) ^ x) = ¬x v y";
questionAnswer["Kí hiệu ^ là phép nhân logic. Kết quả nào sai"] = "1 ^ 1 = 0";
questionAnswer["Kết quả nào đúng khi đối 3B25 từ hệ 16 sang hệ 2"] = "11101100100101";
questionAnswer["Đổi số 12.125 từ hệ thập phân sang hệ nhị phân."] = "1100.001.";
questionAnswer["Đặc điểm nào đúng cho biểu diễn số dấu phẩy tĩnh?"] = "Là \"Độ rộng (số bít) cố định.\" và \"Số bít cho phần nguyên và phẩn lẻ cố định.\"";
questionAnswer["Kết quả nào là đúng khi đổi số thập phân 59 ra hệ nhị phân"] = "111011";
questionAnswer["Kết quả nào đúng khi đổi B9D4 từ hệ 16 sang hệ 10"] = "47572";
questionAnswer["Kết quả nào là đúng khi đổi số hệ hệ thập phân 675 ra Hexa (16)"] = "2A3";
questionAnswer["Kết quả nào đúng khi đổi 2468 từ 10 sang 16"] = "9A4";
questionAnswer["Kết quả nào đúng khi đổi 111011000101 từ hệ 2 sang 10"] = "3781";
questionAnswer["Kết quả nào đúng khi đổi 1357 từ hệ 16 sang hệ 10"] = "4951";
questionAnswer["Kết quả nào là đúng khi đổi số nhị phân 1011011.011 ra hệ Hexa (16)"] = "5B.6";
questionAnswer["Kết quả nào là đúng khi đổi số Hexa FA.32 ra hệ nhị phân"] = "11111010.0011001";
questionAnswer["Biểu diễn nhị phân của số thập phân 123 là:"] = "1111011";
questionAnswer["Kết quả nào là đúng khi đổi số nhị phân 10011011 ra hệ thập phân"] = "155";
questionAnswer["Kết quả nào đúng khi đổi 963 từ 10 sang 16"] = "3C3";
questionAnswer["Kết quả nào đúng khi đổi 265 từ hệ đếm cơ số 10 sang hệ đếm cơ số 2"] = "100001001";
questionAnswer["Biểu diễn bát phân của số nhị phân 1100001001 là gì?"] = "1411.";
questionAnswer["Kết quả nào đúng khi đối C91F từ hệ 16 sang hệ 2"] = "1100100100011111";
questionAnswer["Biểu diễn thập lục phân của số nhị phân 111100100001111 là gì?"] = "790F.";
questionAnswer["Cho phép toán A xác định như sau 0 A 0 = 1, 1 A 0 = 0, 0 A 1 = 0, 1 A 1 = 0, hỏi A có thể biểu diễn qua phép hội (AND) ^ và phép phủ định ¬ (NOT) như thế nào?"] = "a A b = (¬a) ^ (¬b).";
questionAnswer["Chọn câu đúng và đầy đủ nhất về hệ hàm đầy đủ trong đại số Boole:"] = "Là hệ ba hàm nhân, cộng và phủ định logic";
questionAnswer["Cột nào là kết quả của phép cộng logic"] = "Cột B";
questionAnswer["Cột nào là kết quả của phép nhân logic x và y"] = "Cột A";
questionAnswer["Cho phép toán A xác định như sau 0 A 0 = 1, 1 A 0 = 1, 0 A 1 = 1, 1 A 1 = 0, hỏi kết quả của phép tính 0101 A 1001 bằng bao nhiêu?"] = "1110.";
questionAnswer["Kết quả nào sai đối với phép toán cộng Logic V"] = "0 V 0 = 1";
questionAnswer["Có bao nhiêu hàm đại số logic hai ngôi?"] = "16.";
questionAnswer["Hàm đơn điệu chặt ký hiệu qua < được định nghĩa như sau: 0<1 =1 còn tất cả các trường hợp khác đều bằng 0. Biểu diễn nào là đúng đối với phép toán > nói trên"] = "(¬x^y)";
questionAnswer["3"] = "- 1 \n- 1 Φ 0 = 0 \n- (¬x ^ y) \n- Chữ nhỏ đáp án là Cột D \n- Chữ lớn đáp án là Cột C";
questionAnswer["Phép toán kéo theo (x  y) nhận biểu diễn nào"] = "(\¬ x v \¬y)";
questionAnswer["Trong phép toán cộng theo module 2 kí hiệu qua dấu  biểu thức nào sai"] = "1 ⨁ 0 = 0";
questionAnswer[""] = "";
questionAnswer["x"] = "Cột C";

var button = document.createElement("button");
button.innerHTML = "Qua Môn :)";
document.getElementById("block-region-side-pre").append(button);
var nextPage = document.createElement("button");
nextPage.style.margin = "10px"
nextPage.innerHTML = "Next Page";
var questionArea = document.createElement("textarea");
questionArea.setAttribute("id", "question-area");
questionArea.placeholder = "Type your question here"
questionArea.style.width = "95%";
questionArea.style.height = "50px";
var answerArea = document.createElement("textarea");
answerArea.style.width = "95%";
answerArea.style.height = "150px";

button.insertAdjacentElement("afterend", nextPage);
nextPage.insertAdjacentElement("afterend", questionArea);
questionArea.insertAdjacentElement("afterend", answerArea);

button.addEventListener("click", function () {
    var content = document.getElementsByClassName('que multichoice deferredfeedback notyetanswered'); // html elements contains questions

    for (let i = 0; i < content.length; i++) {
        let answerList = content[i].childNodes[1].childNodes[0].childNodes[3].childNodes[1].children; // list of answers
        let question = content[i].childNodes[1].childNodes[0].childNodes[2].textContent.split('\n')[0]; // current question

        if (Object.keys(questionAnswer).includes(question)) {
            for (let j = 0; j < answerList.length; j++) {
                if (questionAnswer[question].trim() == answerList[j].textContent.slice(3).trim()) {
                    answerList[j].childNodes[0].setAttribute("checked", true);
                }
            }
        }
    }
});

nextPage.addEventListener("click", function () {
    document.getElementsByClassName("mod_quiz-next-nav btn btn-primary")[0].click();
});

questionArea.addEventListener("input", function () {
    answerArea.value = questionAnswer[questionArea.value];
});

questionArea.addEventListener("focus", function () {
    questionArea.value = "";
})
